## Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [1]:
import numpy as np

In [25]:
N = int(input('Введите положительное число.'))
if N >= 0:
    A = np.array([n for n in range(N-1,-1,-1)])
A

Введите положительное число.2


array([1, 0])

## Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [50]:
N = int(input('Введите положительное число.'))
x, y = np.mgrid[0:N+1, 0:N+1]
x = x[::-1]
print("\nМатрица x:\n",x)
print("\nДиагональная матрица:\n",x.diagonal())

Введите положительное число.6

Матрица x:
 [[6 6 6 6 6 6 6]
 [5 5 5 5 5 5 5]
 [4 4 4 4 4 4 4]
 [3 3 3 3 3 3 3]
 [2 2 2 2 2 2 2]
 [1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0]]

Диагональная матрица:
 [6 5 4 3 2 1 0]


In [42]:
print('Сумма x:                   ',x.sum())

Сумма x:                    224


In [38]:
print('Сумма диагональной матрицы:',x.diagonal().sum())

Сумма диагональной матрицы: 28


## Задание 3
Решите систему уравнений:
* 4x + 2y + z = 4
* x + 3y = 12
* 5y + 4z = -3

In [2]:
from numpy import linalg

In [8]:
a = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
b = np.array([4, 12, -3])
x = np.linalg.solve(a, b)
print('x='+str(x[0])+';','y='+str(x[1])+';','z='+str(x[2]))

x=0.4666666666666668; y=3.844444444444444; z=-5.555555555555555


In [16]:
print('4x + 2y + z =',4*x[0]+2*x[1]+x[2])
print('     x + 3y =',x[0]+3*x[1])
print('    5y + 4z =',5*x[1]+4*x[2])

4x + 2y + z = 4.0
     x + 3y = 11.999999999999998
    5y + 4z = -3.0


## Задание 4
Вам подаются на вход два вектора a и b в трехмерном пространстве.Заполните их случайными числами. Реализуйте их скалярное произведение с помощью NumPy.

In [78]:
a = np.random.randint(0, 99, 3)
b = np.random.randint(0, 99, 3)
print('__'*10,'\nCкалярное произведение:\n',np.dot(a, b))
print('__'*10,'\n'+str(a))
print('__'*10,'\n'+str(b))

____________________ 
Cкалярное произведение:
 2857
____________________ 
[75 22 18]
____________________ 
[19  7 71]


##### 