## Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [23]:
import numpy as np

In [25]:
N = int(input('Введите положительное число.'))
if N >= 0:
    A = np.array([n for n in range(N-1,-1,-1)])
A

Введите положительное число.2


array([1, 0])

## Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [37]:
N = int(input('Введите положительное число.'))
if N >= 0:
    A = np.array([n for n in range(N-1,-1,-1)])
A_tr = np.matrix(A).T
A_tr

Введите положительное число.9


matrix([[8],
        [7],
        [6],
        [5],
        [4],
        [3],
        [2],
        [1],
        [0]])

In [38]:
print('Сумма:',A_tr.sum())

Сумма: 36


## Задание 3
Решите систему уравнений:
* 4x + 2y + z = 4
* x + 3y = 12
* 5y + 4z = -3

In [2]:
from numpy import linalg

In [8]:
a = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
b = np.array([4, 12, -3])
x = np.linalg.solve(a, b)
print('x='+str(x[0])+';','y='+str(x[1])+';','z='+str(x[2]))

x=0.4666666666666668; y=3.844444444444444; z=-5.555555555555555


In [16]:
print('4x + 2y + z =',4*x[0]+2*x[1]+x[2])
print('     x + 3y =',x[0]+3*x[1])
print('    5y + 4z =',5*x[1]+4*x[2])

4x + 2y + z = 4.0
     x + 3y = 11.999999999999998
    5y + 4z = -3.0


## Задание 4
Вам подаются на вход два вектора a и b в трехмерном пространстве.Заполните их случайными числами. Реализуйте их скалярное произведение с помощью NumPy.

In [90]:
a = np.random.rand(2, 2, 2)
b = np.random.rand(2, 2, 2)
print('__'*10)
print('Cкалярное произведение:')
print(np.dot(a, b))
print('__'*10)
print(a)
print('__'*10)
print(b)

____________________
Cкалярное произведение:
[[[[0.95584625 0.83084822]
   [1.22004757 0.31141408]]

  [[0.66284786 0.4845737 ]
   [0.78516259 0.22834896]]]


 [[[0.19625573 0.26275318]
   [0.31178115 0.05146929]]

  [[0.90975392 0.686656  ]
   [1.09198008 0.31048698]]]]
____________________
[[[0.97010838 0.72250961]
  [0.36431708 0.63597801]]

 [[0.50952479 0.0125654 ]
  [0.57269662 0.84107866]]]
____________________
[[[0.3646221  0.5040129 ]
  [0.83337755 0.47321319]]

 [[0.58979183 0.0934803 ]
  [0.89671552 0.3055019 ]]]


In [91]:
n = [2,2,2]

print(n)
a = np.random.rand(int(n[0]),int(n[1]),int(n[2]))
b = np.random.rand(int(n[0]),int(n[1]),int(n[2]))
print('__'*10)
print('Cкалярное произведение:',np.dot(a, b))
print('__'*10)
print(a)
print('__'*10)
print(b)

[2, 2, 2]
____________________
Cкалярное произведение: [[[[0.67415216 0.67384026]
   [1.02308298 0.94733381]]

  [[0.3756668  0.37901826]
   [0.57128295 0.533597  ]]]


 [[[0.6038936  0.40079234]
   [0.84875557 0.52057293]]

  [[0.67169868 0.61505537]
   [1.00055522 0.85277723]]]]
____________________
[[[0.62726195 0.78920311]
  [0.35907921 0.43575268]]

 [[0.0129212  0.93855672]
  [0.47250631 0.85065712]]]
____________________
[[[0.26988591 0.54644412]
  [0.63971237 0.41950754]]

 [[0.50193447 0.82674043]
  [0.89740978 0.54327078]]]


##### 